### ISSUE TITLE
bug: unable to install on mac Monterey

### ISSUE THREAD

**Issue by jaepetto** [asdf-vm/asdf#1153]
### Describe the Bug

After upgrading my machine from Mojave to Monterey, asdf does not work anymore.

## cleanup
- `rm -rf ~/.asdf`
- edit `.zshrc` to make sure that the asdf plugin is not loaded and the completion script is not sourced

### followed steps
Followed instructions at https://asdf-vm.com/guide/getting-started.html#_3-install-asdf (ZSH & Homebrew)
```shell
$ brew install asdf
==> Downloading https://ghcr.io/v2/homebrew/core/asdf/manifests/0.9.0
Already downloaded: /Users/jaep/Library/Caches/Homebrew/downloads/4c8b74032c7b9ff0c90697b21044b2b6d4d67781143536711bf7dcd49daaec0b--asdf-0.9.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/asdf/blobs/sha256:2c1733505b491d9d5a9442655c123c68fd3a3b4e102c89bab39898246a
Already downloaded: /Users/jaep/Library/Caches/Homebrew/downloads/bec5c845753b610664e42529bde8f713c8f859ff7e62595689cb7abe7cd72029--asdf--0.9.0.all.bottle.tar.gz
==> Pouring asdf--0.9.0.all.bottle.tar.gz
==> Caveats
To use asdf, add the following line to your ~/.zshrc:
  . /usr/local/opt/asdf/libexec/asdf.sh

Restart your terminal for the settings to take effect.

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/asdf/0.9.0: 150 files, 627.4KB
==> Running `brew cleanup asdf`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
```

### result
asdf does not work:
```shell
asdf
Unknown command: `asdf `
/usr/local/Cellar/asdf/0.9.0/libexec/bin/asdf: line 82: /usr/local/opt/asdf/lib/commands/command-help.bash: No such file or directory
```

### followed steps
Followed instructions at https://asdf-vm.com/guide/getting-started.html#_3-install-asdf (ZSH & Homebrew)
```shell
$ brew install asdf
==> Downloading https://ghcr.io/v2/homebrew/core/asdf/manifests/0.9.0
Already downloaded: /Users/jaep/Library/Caches/Homebrew/downloads/4c8b74032c7b9ff0c90697b21044b2b6d4d67781143536711bf7dcd49daaec0b--asdf-0.9.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/asdf/blobs/sha256:2c1733505b491d9d5a9442655c123c68fd3a3b4e102c89bab39898246a
Already downloaded: /Users/jaep/Library/Caches/Homebrew/downloads/bec5c845753b610664e42529bde8f713c8f859ff7e62595689cb7abe7cd72029--asdf--0.9.0.all.bottle.tar.gz
==> Pouring asdf--0.9.0.all.bottle.tar.gz
==> Caveats
To use asdf, add the following line to your ~/.zshrc:
  . /usr/local/opt/asdf/libexec/asdf.sh

Restart your terminal for the settings to take effect.

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/asdf/0.9.0: 150 files, 627.4KB
==> Running `brew cleanup asdf`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

Update `~/.zshrc` plugins line to add `asdf`

### result
asdf does not work:
```shell
asdf
Unknown command: `asdf `
/usr/local/Cellar/asdf/0.9.0/libexec/bin/asdf: line 82: /usr/local/opt/asdf/lib/commands/command-help.bash: No such file or directory
```

## installation with ZSH & git

followed the instructions at https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/asdf and https://asdf-vm.com/guide/getting-started.html#_3-install-asdf

```shell
$ rm -rf ~/.asdf
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf
```

Update `~/.zshrc` plugins line to add `asdf`

### results
asdf does not work:
```shell
$ asdf
zsh: command not found: asdf

$ ~/.asdf/bin/asdf
Unknown command: `asdf `
/Users/jaep/.asdf/bin/asdf: line 82: /usr/local/opt/asdf/lib/commands/command-help.bash: No such file or directory
```

### Expected Behaviour

no error should happen and the environment should be taken into account.

### Actual Behaviour

asdf is unusable.

### Environment

```shell
mac os monterey + zsh (oh-my-zsh)
```

**Comment by jaepetto** [comment]
This issue was actually resolved by killing tmux session and restarting it as stated in https://github.com/Homebrew/homebrew-core/issues/91995#issuecomment-1001058562

**Comment by dimitarvp** [comment]
I don't use `tmux` and as of 2023-JUN-19 and at ASDF 0.12.0 this problem still exists.

**Comment by JonathanCrider** [comment]
> And here's exactly what fixed it (have that in `~/.zshrc` or your own dotfiles that get called by it):
> 
> export ASDF_DIR=$(brew --prefix asdf)/libexec
> . $(brew --prefix asdf)/libexec/asdf.sh
> . $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash
> Credit: [#1103 (comment)](https://github.com/asdf-vm/asdf/issues/1103#issuecomment-986386458)

Still an issue in February 2025, here's my current working solution (asdf v0.15.0)

`ASDF_DIR=$(brew --prefix asdf)/libexec
. $(brew --prefix asdf)/libexec/asdf.sh
. $(brew --prefix asdf)/etc/bash_completion.d/asdf`
