### ISSUE TITLE
bug: lastest version installed from homebrew seems broken

### ISSUE THREAD

**Issue by babeal** [asdf-vm/asdf#1393]
### Describe the Bug

The command asdf works, I can install tools and versions.  However, the tools are not available on path ("python", "npm", "node").  I think the problem is that asdf.sh.. its missing.  It doesn't exist here HOME/.asdf/asdf.sh. It doesn't exist in the old recommendation of {brew --prefix asdf}/asdf.sh either.  Is this version broken or is there a way to fix this?  I have tried uninstalling asdf and deleting the entire .asdf directory and reinstalling...it results in the same behavior.  No asdf.sh in the correct locations indicated by the documentation.

### Steps to Reproduce

1. brew install asdf
2. Add asdf.sh to profile
3. asdf plugin add nodejs
4. asdf global nodejs lts
5. asdf install
6. npm --version -> command not found

### Expected Behaviour

shims should work

### Actual Behaviour

shims don't work any more

### Environment

```shell
OS:
Darwin 3c22fbb81b82.ant.amazon.com 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.11.0

ASDF ENVIRONMENT VARIABLES:


ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
python                       https://github.com/danhper/asdf-python.git master 8505457
```

### asdf plugins affected (if relevant)

all

**Comment by dave-hay** [comment]
Had the same issue found solution here https://github.com/asdf-vm/asdf/issues/785#issuecomment-1106950614. 

Run `rm -rf ~/.asdf/shims; asdf reshim` and that should fix it.

**Comment by jthegedus** [comment]
Yes, this was expected as the underlying cause of the Homebrew issues as seen in prior versions still exists. Please read the existing Homebrew threads as linked above (thanks @dave-hay 🙏 )
