### ISSUE TITLE
asdf: command not found

### ISSUE THREAD

**Issue by antonovga** [asdf-vm/asdf#279]
MacOS

previously installed `rvm` and trying to install `asdf`
getting error `asdf: command not found`

$PATH "mess" after adding to `.bash_profile`
```
PATH=/Users/grg/.asdf
Saving session...
...copying shared history...
...saving history...
...completed./bin:/Users/grg/.asdf
Saving session...
...copying shared history...
...saving history...
...completed./shims:/Users/grg/.rvm/gems/ruby-2.5.0/bin:/Users/grg/.rvm/gems/ruby-2.5.0@global/bin:/Users/grg/.rvm/rubies/ruby-2.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/grg/.rvm/bin
``` 

quick fix from https://github.com/asdf-vm/asdf/issues/98
`touch $HOME/.bash_sessions_disable`
fixes the problem

Maybe add this as a last point to the installation guide for macos?

**Comment by Stratus3D** [comment]
This is related to #92.

Yes, I think adding it to the README would be a good idea. We should note the versions of OSX that require this change in the README.

**Comment by antonovga** [comment]
Another solution
inside `.bash_profile` add
`export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"`

I didn't understand why `asdf.sh`, which purpose is exactly as above string, brakes env when adding to `.bash_profile`

**Comment by apisaka** [comment]
I've solved this with `reshim` as `asdf reshim <plugin_name>`

**Comment by English3000** [comment]
I'm getting `bash: asdf: command not found` as well.

Followed the instructions. This is my `.bash_profile`:
```
source "$HOME/.bashrc"
export PATH="/usr/local/opt/qt@5.5/bin:$PATH"
# don't work
. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash
```

**Comment by Stratus3D** [comment]
@English3000 and you are sure the file is being sourced and that `$HOME/.asdf/asdf.sh` exists?

**Comment by English3000** [comment]
```
~$ $HOME
-bash: /Users/amarkskatz: is a directory
~$ pwd
/Users/amarkskatz
~$ cd .asdf
~/.asdf ((v0.4.3))$ ls -A
.git              asdf.sh
.github           ballad-of-asdf.md
.gitignore        bin
.travis.yml       completions
CHANGELOG.md      defaults
CONTRIBUTING.md   docs
LICENSE           help.txt
README.md         lib
VERSION           lint.sh
Vagrantfile       release.sh
asdf.fish         test
```

It's working now... So the issue went away when I turned my computer off and turned it on the next day.

**Comment by Stratus3D** [comment]
@antonovga I think this issue has been fixed in version 0.5.1. I don't think `touch $HOME/.bash_sessions_disable` should be required anymore. Can you upgrade (`asdf update`) and see if it is fixed for you?

**Comment by Stratus3D** [comment]
Closing as I think this has been fixed.

**Comment by danikgan** [comment]
> Another solution inside `.bash_profile` add `export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"`
> 
> I didn't understand why `asdf.sh`, which purpose is exactly as above string, brakes env when adding to `.bash_profile`

This is still an issue as of today and I'd suggest including this fix in the ReadME for python installation here: https://github.com/asdf-community/asdf-python
